### ISSUE TITLE
Re-release as a npm

### ISSUE THREAD

**Issue by zeroasterisk** [vazco/universe-react-flipcard#1]
I like this simple little card... an excellent utility.  

Can you release it as a NPM vs a Meteor package?

Have you considered using https://github.com/kadirahq/react-cdk to develop the UI?
Bonus, it will publish the StoryBook as a webpage demo/playground for your component too.

**Comment by radekmie** [comment]
We've decided to archive some of our repositories as we are no longer using nor willing to maintain them. Part of this process involves closing related issues and PRs. If you still need help, do contact us on opensource@vazco.eu.
